apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: parimal5/vprofileapp:latest
          ports:
            - name: vproapp-port
              containerPort: 8080
      initContainers:
        - name: init-mydb
          image: busybox
          #vprodb.default.svc.cluster.local
          # vprodb -name of the Service
          # default - name of the namespace we did not create any so deafult
          # until nslookup vprodb.default; do echo waiting for vprodb; sleep 2; done - This also should work
          command:
            [
              "sh",
              "-c",
              "until nslookup vprodb.default.svc.cluster.local; do echo waiting for vprodb; sleep 2; done",
            ]
        - name: init-memcache
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprocache01.default.svc.cluster.local; do echo waiting for vprocache01; sleep 2; done",
            ]
